// This file is autogenerated by tools/update-file-sizes.js
VIZ.fileSizes = {
  "data/marey-header.json": 2301,
  "data/marey-trips.json": 990166,
  "data/spider.json": 2849,
  "data/station-network.json": 8772
};
VIZ.fileHashes = {
  "data/marey-header.json": "189cefd7",
  "data/marey-trips.json": "54288daf",
  "data/spider.json": "f6fdad16",
  "data/station-network.json": "1b709f2c"
};